import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../src/store.js';
const p={event_id:'55',event_value:'1',event_source:'0',Host:'Router',Event:'Enlace caído',event_nseverity:'5'};
function setup(path=':memory:'){const s=new Store(path);s.saveConfig({groups:['1@g.us'],minSeverity:0,hostContains:'',tag:'',updates:true});return s;}
function due(s){return s.db.prepare('SELECT due FROM reminders LIMIT 1').get().due;}
function reminders(s){return s.snapshot().jobs.filter(j=>j.kind==='reminder');}
test('Desastre repite después del intervalo, sin acumular pendientes',()=>{const s=setup();s.accept(p);assert.equal(s.config().reminderMinutes,1);s.enqueueReminders(due(s));assert.equal(reminders(s).length,0);s.sent(s.nextJob().id);const deadline=due(s);s.enqueueReminders(deadline-1);assert.equal(reminders(s).length,0);s.enqueueReminders(deadline+3600000);assert.equal(reminders(s).length,1);s.enqueueReminders(deadline+7200000);assert.equal(reminders(s).length,1);assert.match(reminders(s)[0].message,/ALERTA CRÍTICA/);s.db.close();});
test('recuperación cancela recordatorios incluso si un envío falla después',()=>{const s=setup();s.accept(p);s.sent(s.nextJob().id);s.enqueueReminders(due(s));const job=s.nextJob();s.accept({...p,event_value:'0',problem_status:'Resolved'});s.failed(job,'error tardío');assert.equal(reminders(s)[0].status,'cancelled');assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM reminders').get().n,0);s.enqueueReminders(Date.now()+999999);assert.equal(reminders(s).length,1);assert.match(s.nextJob().message,/RECUPERADO/);assert.throws(()=>s.retry(job.id));s.db.close();});
test('reconocimiento mantiene la programación; bajada de severidad la cancela',()=>{const s=setup();s.accept(p);s.sent(s.nextJob().id);const deadline=due(s);s.accept({...p,event_update_status:'1',problem_status:'Reconocido'});s.sent(s.nextJob().id);assert.equal(due(s),deadline);s.accept({...p,event_update_status:'1',problem_status:'Reconocido',event_nseverity:'4'});assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM reminders').get().n,0);s.accept({...p,event_update_status:'1',problem_status:'Vuelve a Desastre'});assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM reminders').get().n,1);s.db.close();});
test('panel desactiva y cambia intervalo de incidentes existentes sin cambiar destinos',()=>{const s=setup();s.accept(p);s.sent(s.nextJob().id);s.enqueueReminders(due(s));s.saveConfig({...s.config(),remindersEnabled:false});assert.equal(reminders(s)[0].status,'cancelled');s.enqueueReminders(Date.now()+999999);assert.equal(reminders(s).length,1);s.saveConfig({...s.config(),groups:['2@g.us'],remindersEnabled:true,reminderMinutes:5});assert.ok(due(s)>=Date.now()+299000);s.enqueueReminders(due(s));assert.equal(reminders(s)[0].destination,'1@g.us');assert.throws(()=>s.saveConfig({...s.config(),reminderMinutes:0}));assert.throws(()=>s.saveConfig({...s.config(),reminderMinutes:1.5}));s.db.close();});
test('reinicio conserva programación, y severidades menores no programan',()=>{const dir=mkdtempSync(join(tmpdir(),'reminders-'));const path=join(dir,'db');try{let s=setup(path);s.accept(p);s.sent(s.nextJob().id);const deadline=due(s);s.db.close();s=new Store(path);assert.equal(due(s),deadline);s.enqueueReminders(deadline+3600000);assert.equal(reminders(s).length,1);s.accept({...p,event_id:'56',event_nseverity:'4'});assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM reminders').get().n,1);s.db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
