import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../src/store.js';
const p={event_source:'0',event_id:'42',Host:'router-1',Event:'Sin conexión',event_nseverity:'4',event_severity:'Alta',event_value:'1',event_update_status:'0',event_date:'2026.09.30',event_time:'10:00:00',event_tags:'[{"tag":"equipo","value":"redes"}]',problem_status:'Active'};
function setup(){const s=new Store(':memory:');s.saveConfig({groups:['111@g.us'],minSeverity:3,hostContains:'router',tag:'equipo=redes',updates:true});return s;}
test('problema duplicado, actualización y recuperación mantienen destinos y estado',()=>{const s=setup();assert.equal(s.accept(p).queued,1);assert.equal(s.accept(p).duplicate,true);s.saveConfig({...s.config(),groups:['222@g.us'],minSeverity:5});s.accept({...p,event_update_status:'1',event_update_date:'2026.09.30',event_update_time:'10:01:00',problem_status:'Reconocido'});s.accept({...p,event_value:'0',problem_status:'Resolved',event_recovery_time:'10:05:00'});const h=s.snapshot();assert.equal(h.incidents[0].status,'recovered');assert.equal(h.jobs.length,3);assert.ok(h.jobs.every(j=>j.destination==='111@g.us'));assert.match(h.jobs[0].message,/RECUPERADO/);});
test('recuperación adelantada no permite reapertura ni problema tardío',()=>{const s=setup();s.accept({...p,event_value:'0',problem_status:'Resolved'});assert.equal(s.accept(p).queued,0);assert.equal(s.snapshot().incidents[0].status,'recovered');assert.equal(s.snapshot().jobs.length,1);});
test('filtros no generan envíos y tampoco recuperación a destinos nuevos',()=>{const s=setup();s.accept({...p,Host:'otro'});s.saveConfig({...s.config(),hostContains:''});s.accept({...p,Host:'otro',event_value:'0',problem_status:'Resolved'});assert.equal(s.snapshot().jobs.length,0);});
test('una recuperación espera los reintentos del problema; falla terminal permite avanzar',()=>{const s=setup();s.accept(p);const first=s.nextJob();s.failed(first,'sin conexión');s.accept({...p,event_value:'0',problem_status:'Resolved'});assert.equal(s.nextJob(),undefined);s.db.prepare("UPDATE jobs SET status='failed' WHERE id=?").run(first.id);const recovery=s.nextJob();assert.match(recovery.message,/RECUPERADO/);s.sent(recovery.id);assert.throws(()=>s.retry(first.id),/estado anterior/);});
test('validación rechaza eventos incompletos y otros orígenes',()=>{const s=setup();for(const x of [{},{...p,event_id:'{EVENT.ID}'},{...p,event_source:'1'},{...p,event_nseverity:'NaN'}])assert.throws(()=>s.accept(x));assert.equal(s.snapshot().jobs.length,0);});
test('dos actualizaciones distintas se guardan y sus reintentos se deduplican',()=>{const s=setup();s.accept(p);const u={...p,event_update_status:'1',event_update_date:'2026.09.30',event_update_time:'10:01:00',problem_status:'Reconocido'};s.accept(u);assert.equal(s.accept(u).duplicate,true);s.accept({...u,problem_status:'Comentario nuevo'});assert.equal(s.snapshot().jobs.length,3);});
